### ISSUE TITLE
目前node端渲染会报错

### ISSUE THREAD

**Issue by uuid1017** [uxcore/uxcore-uploader#18]
问题在于uxcore-uploader的util.js里面直接使用了document而没判断是否存在这个对象；以及uxcore-uploader的依赖uploadercore里面也有多处没有判断document直接使用的地方。手动试了下，改好这几处之后即可node端渲染不再报错

**Comment by eternalsky** [comment]
a pr ?

**Comment by uuid1017** [comment]
问题是这里涉及的依赖也需要改动

**Comment by eternalsky** [comment]
fix in cb66c79b37d8c89f9e2f8fedbbfc1f6511d9f3d0
