### ISSUE TITLE
accept参数在windows下不生效（还是可选择的）

### ISSUE THREAD

**Issue by FE-Girl** [uxcore/uxcore-uploader#31]
![image](https://cloud.githubusercontent.com/assets/6926706/18157681/7ecb886a-7051-11e6-930c-731edda7b82e.png)

![image](https://cloud.githubusercontent.com/assets/6926706/18157653/62fae428-7051-11e6-8011-312535a3372c.png)

![image](https://cloud.githubusercontent.com/assets/6926706/18157715/ac8e4d0a-7051-11e6-9255-86223eda31ff.png)

**Comment by yanbingbing** [comment]
什么浏览器? 并不是所有浏览器支持accept

**Comment by eternalsky** [comment]
reopen if issue still exits
