### ISSUE TITLE
IE11下，默认使用的是flash上传而不是h5

### ISSUE THREAD

**Issue by WisestCoder** [uxcore/uxcore-uploader#41]

**Comment by eternalsky** [comment]
标题请重新修正一下

**Comment by WisestCoder** [comment]
![](https://raw.githubusercontent.com/dushao103500/temp-repository/master/ie11.png)
![](https://raw.githubusercontent.com/dushao103500/temp-repository/master/uploadError.png)

**Comment by WisestCoder** [comment]
你们文档中说 IE11下使用的是h5，但这边显示的是flash

**Comment by yanbingbing** [comment]
俩种情况：

1. IE11可能不支持某些特性
2. 虽然是IE11，但文档模式可能是IE9，IE10，某些特性不能使用

**Comment by WisestCoder** [comment]
如果是使用flash发起的，那只能通过在根目录下放一个crossdomain来解决吗？ 没有其他的方法了吗？

**Comment by yanbingbing** [comment]
如果是flash发起的，如果不跨域，crossdomain可以没有，如果跨域，必须有，建议你先检查下IE11下那个网页的文档模式

**Comment by WisestCoder** [comment]
我看过了，应该不是你们的问题，是我们的项目在<meta>里面设置了content为IE9，导致默认的文档模式为IE9，就算改成了edge，刷新页面就又更换成了IE9~~~  非常感谢您的及时回馈解答
