### ISSUE TITLE
传入type为outline的button之后，hover显示的样式不对

### ISSUE THREAD

**Issue by uuid1017** [uxcore/uxcore-uploader#66]
目前是直接设置的`.kuma-upload-picker:hover .kuma-button`的hover效果，而这个样式是与secondary类型的button配套的，如果手动传入type为primary或者outline的button，那么hover效果会错乱。因此可以应该针对不同的type的button设置不同的hover样式

**Comment by alex-mm** [comment]
@Edward67 直接 PR 吧

**Comment by uuid1017** [comment]
已提pr
