### ISSUE TITLE
设置sizeLimit之后，在浏览器的弹窗中依然可以选中超过sizeLimit数量的文件

### ISSUE THREAD

**Issue by uuid1017** [uxcore/uxcore-uploader#68]
设置sizeLimit之后，在浏览器的弹窗中依然可以选中超过sizeLimit数量的文件。点击确定之后拿到的是sizeLimit数量的返回结果，这里能够做到无法选中超过sizeLimit数量的文件吗？

版本：uxcore 0.17.x 整包

**Comment by lzf0402** [comment]
选取文件 已经是系统层面了 目前input type=“file”标签应该只支持accept属性限制文件类型，多选模式下 没法做到限制数量
