### ISSUE TITLE
请问分片上传的话，如何判断该分片属于哪个文件呢？

### ISSUE THREAD

**Issue by wisteriaflash** [uxcore/uxcore-uploader#69]
content-range:bytes 0-1048575/3957390
我看到requestHeader中，有这样的标识，这个只是分片的区间吧？
其他还有什么标识么？

**Comment by yanbingbing** [comment]
分片请求之前，应该有个准备请求，叫transaction请求，会从服务端获得分片请求的sessionid，从第一个分片开始要把sessionid发送给服务端，要不然当然识别不了

**Comment by wisteriaflash** [comment]
好的，明白了
