### ISSUE TITLE
图片上传模式加号框顶部不对齐

### ISSUE THREAD

**Issue by javaxiu** [uxcore/uxcore-uploader#79]
<img width="324" alt="20180912162250" src="https://user-images.githubusercontent.com/4281225/45412458-3c2b5080-b6a9-11e8-9d90-ab5678c2e019.png">
在safari下，图片上传模式加号框出现顶部不对齐。需要增加样式

`.kuma-upload-fileitem-visual{
  vertical-align: top;
}`

**Comment by lzf0402** [comment]
fixed in v3.3.5
