### ISSUE TITLE
打包了2个uploadcore代码，导致体积增大100kb，js执行时间增加

### ISSUE THREAD

**Issue by uuid1017** [uxcore/uxcore-uploader#81]
webpack打包分析
![image](https://user-images.githubusercontent.com/7688659/48930514-ec2ffc00-ef2b-11e8-9b0d-50d8add73cfa.png)

![image](https://user-images.githubusercontent.com/7688659/48930451-9d826200-ef2b-11e8-9487-5d74c715893c.png)
在第一个文件里直接调用了 dist 目录下。
![image](https://user-images.githubusercontent.com/7688659/48930493-c9054c80-ef2b-11e8-920c-4d321bfd1236.png)
在其他文件里没有显示的调用 dist 目录

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-uploader/commit/77104b219df7936c66b5c9c2ec68615ee1edb1fa
